version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo Install phase...
      - printenv | sort
      - npm install pnpm -g
      - pnpm -v

  build:
    commands:
      - chmod +x ./scripts/*.sh
      - ./scripts/build.sh
      - ./scripts/deploy.sh
